services:
  app:
    build:
      args:
        user: tms_user
        pid: 1000
      context: .
      dockerfile: Dockerfile
    image: tms
    container_name: tms-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tms
  db:
    image: postgres
    container_name: tms-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/pgsql:/docker-entrypoint-initdb.d
    networks:
      - tms

  nginx:
    image: nginx:1.25.3-alpine
    container_name: tms-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tms


networks:
  tms:
    driver: bridge
